version: '3.9'

services:
  backend:
    build:
      context: ./src
      dockerfile: ChatBot.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChatBotDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};
    depends_on:
      - db

  frontend:
    build:
      context: ./src/chat-bot-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  mssql_data:
